#############################################################################
# Makefile for building: scanPos-Alipay
# Generated by qmake (2.01a) (Qt 4.7.3) on: Wed Mar 1 12:44:50 2017
# Project:  scanPos-Alipay.pro
# Template: app
# Command: /home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/qmake -o Makefile scanPos-Alipay.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/include/QtCore -I../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/include/QtNetwork -I../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/include/QtGui -I../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/include/QtSql -I../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/include -I. -Iinclude -I../../../../freedom/openssl-287/include -I. -I.
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib
LIBS          = $(SUBLIBS)  -L/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib /home/kira/freedom/openssl-287/lib/libssl.a /home/kira/freedom/openssl-287/lib/libcrypto.a /opt/kira/lib/libposoffline.so -lQtSql -L/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-none-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = blackclearwidget.cpp \
		busidwidget.cpp \
		buslinewidget.cpp \
		cup8583.cpp \
		cuptrans.cpp \
		cuptransproc.cpp \
		endes.cpp \
		gprsserialtalk.cpp \
		gpsserialtalk.cpp \
		main.cpp \
		myposwidget.cpp \
		mysqlite.cpp \
		networktalk.cpp \
		posidwidget.cpp \
		poswidget.cpp \
		scanserialtalk.cpp \
		setconfig.cpp \
		signalwidget.cpp \
		stmserialtalk.cpp \
		tradedialog.cpp \
		unionpay.cpp \
		unionpaynet.cpp moc_blackclearwidget.cpp \
		moc_busidwidget.cpp \
		moc_buslinewidget.cpp \
		moc_gprsserialtalk.cpp \
		moc_gpsserialtalk.cpp \
		moc_myposwidget.cpp \
		moc_mysqlite.cpp \
		moc_networktalk.cpp \
		moc_posidwidget.cpp \
		moc_poswidget.cpp \
		moc_scanserialtalk.cpp \
		moc_signalwidget.cpp \
		moc_stmserialtalk.cpp \
		moc_tradedialog.cpp \
		moc_unionpay.cpp \
		qrc_disppic.cpp
OBJECTS       = blackclearwidget.o \
		busidwidget.o \
		buslinewidget.o \
		cup8583.o \
		cuptrans.o \
		cuptransproc.o \
		endes.o \
		gprsserialtalk.o \
		gpsserialtalk.o \
		main.o \
		myposwidget.o \
		mysqlite.o \
		networktalk.o \
		posidwidget.o \
		poswidget.o \
		scanserialtalk.o \
		setconfig.o \
		signalwidget.o \
		stmserialtalk.o \
		tradedialog.o \
		unionpay.o \
		unionpaynet.o \
		moc_blackclearwidget.o \
		moc_busidwidget.o \
		moc_buslinewidget.o \
		moc_gprsserialtalk.o \
		moc_gpsserialtalk.o \
		moc_myposwidget.o \
		moc_mysqlite.o \
		moc_networktalk.o \
		moc_posidwidget.o \
		moc_poswidget.o \
		moc_scanserialtalk.o \
		moc_signalwidget.o \
		moc_stmserialtalk.o \
		moc_tradedialog.o \
		moc_unionpay.o \
		qrc_disppic.o
DIST          = ../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/g++.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/unix.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/linux.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/qws.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qconfig.pri \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/modules/qt_webkit_version.pri \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_functions.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_config.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/exclusive_builds.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_pre.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/release.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_post.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/warn_on.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/unix/thread.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/moc.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/resources.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/uic.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/yacc.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/lex.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/include_source_dir.prf \
		scanPos-Alipay.pro
QMAKE_TARGET  = scanPos-Alipay
DESTDIR       = 
TARGET        = scanPos-Alipay

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_blackclearwidget.h ui_busidwidget.h ui_buslinewidget.h ui_myposwidget.h ui_posidwidget.h ui_poswidget.h ui_signalwidget.h ui_tradedialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: scanPos-Alipay.pro  ../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf ../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/g++.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/unix.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/linux.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/qws.conf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qconfig.pri \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/modules/qt_webkit_version.pri \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_functions.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_config.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/exclusive_builds.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_pre.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/release.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_post.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/warn_on.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/unix/thread.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/moc.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/resources.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/uic.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/yacc.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/lex.prf \
		../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/include_source_dir.prf \
		/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtSql.prl \
		/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtCore.prl \
		/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtGui.prl \
		/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile scanPos-Alipay.pro
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/g++.conf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/unix.conf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/linux.conf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/common/qws.conf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/qconfig.pri:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/modules/qt_webkit_version.pri:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_functions.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt_config.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/exclusive_builds.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_pre.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/release.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/default_post.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/warn_on.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/qt.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/unix/thread.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/moc.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/resources.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/uic.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/yacc.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/lex.prf:
../../../../eQt/qt-everywhere-opensource-src-4.7.3/qt/mkspecs/features/include_source_dir.prf:
/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtSql.prl:
/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtCore.prl:
/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtGui.prl:
/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile scanPos-Alipay.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/scanPos-Alipay1.0.0 || $(MKDIR) .tmp/scanPos-Alipay1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/scanPos-Alipay1.0.0/ && $(COPY_FILE) --parents blackclearwidget.h busidwidget.h buslinewidget.h cup8583.h cuptrans.h cuptransproc.h datastructure.h endes.h gprsserialtalk.h gpsserialtalk.h myposwidget.h mysqlite.h networktalk.h posidwidget.h poswidget.h scanserialtalk.h serialdata.h setconfig.h signalwidget.h stmserialtalk.h tradedialog.h unionpay.h unionpaynet.h unionpaystructure.h include/pos_crypto.h .tmp/scanPos-Alipay1.0.0/ && $(COPY_FILE) --parents disppic.qrc .tmp/scanPos-Alipay1.0.0/ && $(COPY_FILE) --parents blackclearwidget.cpp busidwidget.cpp buslinewidget.cpp cup8583.cpp cuptrans.cpp cuptransproc.cpp endes.cpp gprsserialtalk.cpp gpsserialtalk.cpp main.cpp myposwidget.cpp mysqlite.cpp networktalk.cpp posidwidget.cpp poswidget.cpp scanserialtalk.cpp setconfig.cpp signalwidget.cpp stmserialtalk.cpp tradedialog.cpp unionpay.cpp unionpaynet.cpp .tmp/scanPos-Alipay1.0.0/ && $(COPY_FILE) --parents blackclearwidget.ui busidwidget.ui buslinewidget.ui myposwidget.ui posidwidget.ui poswidget.ui signalwidget.ui tradedialog.ui .tmp/scanPos-Alipay1.0.0/ && (cd `dirname .tmp/scanPos-Alipay1.0.0` && $(TAR) scanPos-Alipay1.0.0.tar scanPos-Alipay1.0.0 && $(COMPRESS) scanPos-Alipay1.0.0.tar) && $(MOVE) `dirname .tmp/scanPos-Alipay1.0.0`/scanPos-Alipay1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/scanPos-Alipay1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_blackclearwidget.cpp moc_busidwidget.cpp moc_buslinewidget.cpp moc_gprsserialtalk.cpp moc_gpsserialtalk.cpp moc_myposwidget.cpp moc_mysqlite.cpp moc_networktalk.cpp moc_posidwidget.cpp moc_poswidget.cpp moc_scanserialtalk.cpp moc_signalwidget.cpp moc_stmserialtalk.cpp moc_tradedialog.cpp moc_unionpay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_blackclearwidget.cpp moc_busidwidget.cpp moc_buslinewidget.cpp moc_gprsserialtalk.cpp moc_gpsserialtalk.cpp moc_myposwidget.cpp moc_mysqlite.cpp moc_networktalk.cpp moc_posidwidget.cpp moc_poswidget.cpp moc_scanserialtalk.cpp moc_signalwidget.cpp moc_stmserialtalk.cpp moc_tradedialog.cpp moc_unionpay.cpp
moc_blackclearwidget.cpp: blackclearwidget.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) blackclearwidget.h -o moc_blackclearwidget.cpp

moc_busidwidget.cpp: datastructure.h \
		busidwidget.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) busidwidget.h -o moc_busidwidget.cpp

moc_buslinewidget.cpp: datastructure.h \
		buslinewidget.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) buslinewidget.h -o moc_buslinewidget.cpp

moc_gprsserialtalk.cpp: serialdata.h \
		datastructure.h \
		gprsserialtalk.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) gprsserialtalk.h -o moc_gprsserialtalk.cpp

moc_gpsserialtalk.cpp: serialdata.h \
		gpsserialtalk.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) gpsserialtalk.h -o moc_gpsserialtalk.cpp

moc_myposwidget.cpp: poswidget.h \
		scanserialtalk.h \
		serialdata.h \
		datastructure.h \
		tradedialog.h \
		setconfig.h \
		stmserialtalk.h \
		unionpaystructure.h \
		gprsserialtalk.h \
		gpsserialtalk.h \
		mysqlite.h \
		signalwidget.h \
		blackclearwidget.h \
		busidwidget.h \
		buslinewidget.h \
		posidwidget.h \
		unionpay.h \
		cuptrans.h \
		cuptransproc.h \
		cup8583.h \
		endes.h \
		unionpaynet.h \
		networktalk.h \
		myposwidget.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) myposwidget.h -o moc_myposwidget.cpp

moc_mysqlite.cpp: datastructure.h \
		mysqlite.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) mysqlite.h -o moc_mysqlite.cpp

moc_networktalk.cpp: serialdata.h \
		datastructure.h \
		unionpaynet.h \
		unionpaystructure.h \
		networktalk.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) networktalk.h -o moc_networktalk.cpp

moc_posidwidget.cpp: datastructure.h \
		posidwidget.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) posidwidget.h -o moc_posidwidget.cpp

moc_poswidget.cpp: scanserialtalk.h \
		serialdata.h \
		datastructure.h \
		tradedialog.h \
		poswidget.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) poswidget.h -o moc_poswidget.cpp

moc_scanserialtalk.cpp: serialdata.h \
		datastructure.h \
		scanserialtalk.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) scanserialtalk.h -o moc_scanserialtalk.cpp

moc_signalwidget.cpp: signalwidget.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) signalwidget.h -o moc_signalwidget.cpp

moc_stmserialtalk.cpp: serialdata.h \
		unionpaystructure.h \
		datastructure.h \
		stmserialtalk.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) stmserialtalk.h -o moc_stmserialtalk.cpp

moc_tradedialog.cpp: tradedialog.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) tradedialog.h -o moc_tradedialog.cpp

moc_unionpay.cpp: cuptrans.h \
		cuptransproc.h \
		cup8583.h \
		endes.h \
		unionpaystructure.h \
		setconfig.h \
		unionpaynet.h \
		unionpay.h
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/moc $(DEFINES) $(INCPATH) unionpay.h -o moc_unionpay.cpp

compiler_rcc_make_all: qrc_disppic.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_disppic.cpp
qrc_disppic.cpp: disppic.qrc \
		images/tradeInfo.jpg \
		images/trade.jpg \
		images/uncheck.png \
		images/quick.png \
		images/tickets_money.png \
		images/backglass.png \
		images/tickets.jpg \
		images/trade_money.png \
		images/check.png \
		images/signal.png \
		images/blackClear.png \
		images/background.png
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/rcc -name disppic disppic.qrc -o qrc_disppic.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_blackclearwidget.h ui_busidwidget.h ui_buslinewidget.h ui_myposwidget.h ui_posidwidget.h ui_poswidget.h ui_signalwidget.h ui_tradedialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_blackclearwidget.h ui_busidwidget.h ui_buslinewidget.h ui_myposwidget.h ui_posidwidget.h ui_poswidget.h ui_signalwidget.h ui_tradedialog.h
ui_blackclearwidget.h: blackclearwidget.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic blackclearwidget.ui -o ui_blackclearwidget.h

ui_busidwidget.h: busidwidget.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic busidwidget.ui -o ui_busidwidget.h

ui_buslinewidget.h: buslinewidget.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic buslinewidget.ui -o ui_buslinewidget.h

ui_myposwidget.h: myposwidget.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic myposwidget.ui -o ui_myposwidget.h

ui_posidwidget.h: posidwidget.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic posidwidget.ui -o ui_posidwidget.h

ui_poswidget.h: poswidget.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic poswidget.ui -o ui_poswidget.h

ui_signalwidget.h: signalwidget.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic signalwidget.ui -o ui_signalwidget.h

ui_tradedialog.h: tradedialog.ui
	/home/kira/eQt/qt-everywhere-opensource-src-4.7.3/qt/bin/uic tradedialog.ui -o ui_tradedialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

blackclearwidget.o: blackclearwidget.cpp blackclearwidget.h \
		ui_blackclearwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blackclearwidget.o blackclearwidget.cpp

busidwidget.o: busidwidget.cpp busidwidget.h \
		datastructure.h \
		ui_busidwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o busidwidget.o busidwidget.cpp

buslinewidget.o: buslinewidget.cpp buslinewidget.h \
		datastructure.h \
		ui_buslinewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buslinewidget.o buslinewidget.cpp

cup8583.o: cup8583.cpp cup8583.h \
		endes.h \
		unionpaystructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cup8583.o cup8583.cpp

cuptrans.o: cuptrans.cpp cuptrans.h \
		cuptransproc.h \
		cup8583.h \
		endes.h \
		unionpaystructure.h \
		setconfig.h \
		unionpaynet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cuptrans.o cuptrans.cpp

cuptransproc.o: cuptransproc.cpp cuptransproc.h \
		cup8583.h \
		endes.h \
		unionpaystructure.h \
		setconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cuptransproc.o cuptransproc.cpp

endes.o: endes.cpp endes.h \
		unionpaystructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o endes.o endes.cpp

gprsserialtalk.o: gprsserialtalk.cpp gprsserialtalk.h \
		serialdata.h \
		datastructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gprsserialtalk.o gprsserialtalk.cpp

gpsserialtalk.o: gpsserialtalk.cpp gpsserialtalk.h \
		serialdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpsserialtalk.o gpsserialtalk.cpp

main.o: main.cpp myposwidget.h \
		poswidget.h \
		scanserialtalk.h \
		serialdata.h \
		datastructure.h \
		tradedialog.h \
		setconfig.h \
		stmserialtalk.h \
		unionpaystructure.h \
		gprsserialtalk.h \
		gpsserialtalk.h \
		mysqlite.h \
		signalwidget.h \
		blackclearwidget.h \
		busidwidget.h \
		buslinewidget.h \
		posidwidget.h \
		unionpay.h \
		cuptrans.h \
		cuptransproc.h \
		cup8583.h \
		endes.h \
		unionpaynet.h \
		networktalk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

myposwidget.o: myposwidget.cpp myposwidget.h \
		poswidget.h \
		scanserialtalk.h \
		serialdata.h \
		datastructure.h \
		tradedialog.h \
		setconfig.h \
		stmserialtalk.h \
		unionpaystructure.h \
		gprsserialtalk.h \
		gpsserialtalk.h \
		mysqlite.h \
		signalwidget.h \
		blackclearwidget.h \
		busidwidget.h \
		buslinewidget.h \
		posidwidget.h \
		unionpay.h \
		cuptrans.h \
		cuptransproc.h \
		cup8583.h \
		endes.h \
		unionpaynet.h \
		networktalk.h \
		ui_myposwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myposwidget.o myposwidget.cpp

mysqlite.o: mysqlite.cpp mysqlite.h \
		datastructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlite.o mysqlite.cpp

networktalk.o: networktalk.cpp networktalk.h \
		serialdata.h \
		datastructure.h \
		unionpaynet.h \
		unionpaystructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networktalk.o networktalk.cpp

posidwidget.o: posidwidget.cpp posidwidget.h \
		datastructure.h \
		ui_posidwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posidwidget.o posidwidget.cpp

poswidget.o: poswidget.cpp poswidget.h \
		scanserialtalk.h \
		serialdata.h \
		datastructure.h \
		tradedialog.h \
		ui_poswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o poswidget.o poswidget.cpp

scanserialtalk.o: scanserialtalk.cpp scanserialtalk.h \
		serialdata.h \
		datastructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanserialtalk.o scanserialtalk.cpp

setconfig.o: setconfig.cpp setconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setconfig.o setconfig.cpp

signalwidget.o: signalwidget.cpp signalwidget.h \
		ui_signalwidget.h \
		datastructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalwidget.o signalwidget.cpp

stmserialtalk.o: stmserialtalk.cpp stmserialtalk.h \
		serialdata.h \
		unionpaystructure.h \
		datastructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stmserialtalk.o stmserialtalk.cpp

tradedialog.o: tradedialog.cpp tradedialog.h \
		ui_tradedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tradedialog.o tradedialog.cpp

unionpay.o: unionpay.cpp unionpay.h \
		cuptrans.h \
		cuptransproc.h \
		cup8583.h \
		endes.h \
		unionpaystructure.h \
		setconfig.h \
		unionpaynet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unionpay.o unionpay.cpp

unionpaynet.o: unionpaynet.cpp unionpaynet.h \
		unionpaystructure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unionpaynet.o unionpaynet.cpp

moc_blackclearwidget.o: moc_blackclearwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blackclearwidget.o moc_blackclearwidget.cpp

moc_busidwidget.o: moc_busidwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_busidwidget.o moc_busidwidget.cpp

moc_buslinewidget.o: moc_buslinewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buslinewidget.o moc_buslinewidget.cpp

moc_gprsserialtalk.o: moc_gprsserialtalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gprsserialtalk.o moc_gprsserialtalk.cpp

moc_gpsserialtalk.o: moc_gpsserialtalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gpsserialtalk.o moc_gpsserialtalk.cpp

moc_myposwidget.o: moc_myposwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myposwidget.o moc_myposwidget.cpp

moc_mysqlite.o: moc_mysqlite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mysqlite.o moc_mysqlite.cpp

moc_networktalk.o: moc_networktalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networktalk.o moc_networktalk.cpp

moc_posidwidget.o: moc_posidwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_posidwidget.o moc_posidwidget.cpp

moc_poswidget.o: moc_poswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_poswidget.o moc_poswidget.cpp

moc_scanserialtalk.o: moc_scanserialtalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scanserialtalk.o moc_scanserialtalk.cpp

moc_signalwidget.o: moc_signalwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signalwidget.o moc_signalwidget.cpp

moc_stmserialtalk.o: moc_stmserialtalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stmserialtalk.o moc_stmserialtalk.cpp

moc_tradedialog.o: moc_tradedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tradedialog.o moc_tradedialog.cpp

moc_unionpay.o: moc_unionpay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unionpay.o moc_unionpay.cpp

qrc_disppic.o: qrc_disppic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_disppic.o qrc_disppic.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

